import '../models/gridcontent.dart';
import 'package:flutter/material.dart';
const category_data=[
  gridContent(id: 'c1',
   name: 'Italian',
   color: Colors.green),
   gridContent(id: 'c2',
   name: 'Quick and Easy',
   color: Colors.yellow),
   gridContent(id: 'c3',
   name: 'Hamburgers',
   color: Colors.red),
   gridContent(id: 'c4',
   name: 'German',
   color: Colors.pink),
   gridContent(id: 'c5',
   name: 'Light & Lovely',
   color: Colors.blue),
   gridContent(id: 'c6',
   name: 'Exotic',
   color: Colors.purple), 
   gridContent(id: 'c7',
   name: 'Breakfast',
   color: Colors.orange),
   gridContent(id: 'c8',
   name: 'Asian',
   color: Colors.grey),
   gridContent(id: 'c9',
   name: 'French',
   color: Colors.lime),
   gridContent(id: 'c10',
   name: 'Summer',
   color: Colors.teal),

];